name: Create Distribution ZIP File

on:
  release:
    types: [created]

jobs:
  zip-dist:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set tag name variable
        run: echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Create versioned ZIP archive
        run: |
          mkdir -p release
          cd dist
          zip -r "../release/proampac-holiday-${TAG_NAME}.zip" .

      - name: Upload versioned ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: release/proampac-holiday-${{ env.TAG_NAME }}.zip